### ISSUE TITLE
Empty warehouse

### ISSUE THREAD

**Issue by LAB123-tech** [mlvlab/SPoTr#1]
It is a nice work about 3d point cloud segmentation. I'm looking forward that the author will publish the code as sooner as possible to boost the reasearch in the filed of 3d point cloud. Thank you very much.

**Comment by PJin0** [comment]
Thank you for the interest to our paper.

We're now working on it and planning to make the code available on the first week of June.
Thanks.

**Comment by LAB123-tech** [comment]
邮件已经收到，我是李阿标。
