### ISSUE TITLE
Pretrained Model

### ISSUE THREAD

**Issue by yhhxt** [mlvlab/SPoTr#12]
I'm interested in your project and was wondering if you have provided pretrained models for it. Could you please confirm if pretrained models are available, and if so, where I can find them?

**Comment by cherwinsd** [comment]
> I'm interested in your project and was wondering if you have provided pretrained models for it. Could you please confirm if pretrained models are available, and if so, where I can find them?

Hello, have you found the pre trained model yet？

**Comment by yhhxt** [comment]
> > I'm interested in your project and was wondering if you have provided pretrained models for it. Could you please confirm if pretrained models are available, and if so, where I can find them?
> 
> Hello, have you found the pre trained model yet？

I still haven't found it, but I've moved on to another [job](https://github.com/marios2019/CSN) . I mainly want to achieve semantic segmentation for objects, if your goal is indoor scene segmentation, this work may not help.

**Comment by PJin0** [comment]
Thank you for the interest in our paper.

I uploaded the pre-trained models on the repo.

Thank you.
