### ISSUE TITLE
Shapenet Part Segmentation mIoU

### ISSUE THREAD

**Issue by pooja9798** [mlvlab/SPoTr#13]
The results after Performing Part Segmentation on Shpenet Part dataset, is significantly lower in all aspects. The Instance mIoU, Class mIoUs are much lower ( ins miou~ 82). Any suggestions on how to improve the results or if something is missed.

**Comment by lilinhai1** [comment]
> The results after Performing Part Segmentation on Shpenet Part dataset, is significantly lower in all aspects. The Instance mIoU, Class mIoUs are much lower ( ins miou~ 82). Any suggestions on how to improve the results or if something is missed.

请问：作者没有完整公开Part Segmentation的代码，你是怎么得出这些结果呢？

**Comment by pooja9798** [comment]
There already exists some code for shapenet part, the configs, was also obtained from other published papers, and adjusted according to the supplement. That is how I performed the part segmentation. And since the results are lower, now asking why and if the authors would publish how they got the results?

**Comment by PJin0** [comment]
We appreciate your interest in our paper.

We've just uploaded our config file for performing Part Segmentation.

Please run the code with it.

Thank you.
