### ISSUE TITLE
shaepenet Training indicators and inference

### ISSUE THREAD

**Issue by aaaaasleep** [mlvlab/SPoTr#14]
Problem 1: At the end of the training I didn't find any other metrics except for miou's metrics, and I can't open tcp://localhost:8888 to see the other metrics
Problem 2: The error AttributeError: 'Namespace' object has no attribute 'data_name' occurs when running the reasoning code in the
In segmentation.py, I found that there is no data_transform variable.
I hope you can help me with this, thank you very much!

**Comment by PJin0** [comment]
We appreciate your interest to our paper.

We updated our repo and you can easily run it:)
