### ISSUE TITLE
Shapenet data set input problem for shapenetpart task

### ISSUE THREAD

**Issue by utilpotatocat** [mlvlab/SPoTr#17]
The code cannot be run directly. Please provide a data set input function that is suitable for the shapenet data set.
![image](https://github.com/mlvlab/SPoTr/assets/108716614/b063feb3-a333-40b1-9912-564039b74785)

![image](https://github.com/mlvlab/SPoTr/assets/108716614/c96e1fb5-8a13-4c67-baf2-32209d816325)
the “generate_data_list(cfg)” ， “load_data(data_path, cfg)” functions may need modification
there is no shapenet that shapenetpart  task need

**Comment by kellieda** [comment]
Hello, I have also encountered the same issue as you. Could you please share how you resolved it?

**Comment by PJin0** [comment]
Thank you for your interest in our paper.

We resolve it and you can run it directly.
