### ISSUE TITLE
Question about self-positioning points

### ISSUE THREAD

**Issue by LAB123-tech** [mlvlab/SPoTr#2]
How should I understand zs in formula 3 for calculating self positioning points in the paper? zs is described in the paper as lantent vector? What does latent vecor refer to?

![image](https://user-images.githubusercontent.com/84617754/235434512-4c8099b0-b27e-4938-ac72-b2cd5817f398.png)

**Comment by PJin0** [comment]
Yes, zs is a latent vector, which means learnable parameters.
