### ISSUE TITLE
where is supplement？

### ISSUE THREAD

**Issue by Rurouni-z** [mlvlab/SPoTr#20]
thanks for your great work!

in your [paper](https://arxiv.org/abs/2303.16450), you said 
> More details on SPoTr architectures are in the supplement.

and i did'n find any supplement after References, please give me some cue

**Comment by PJin0** [comment]
Thank you for your interest in our paper.

The supplement is in this [link](https://openaccess.thecvf.com/content/CVPR2023/supplemental/Park_Self-Positioning_Point-Based_Transformer_CVPR_2023_supplemental.pdf).  Thank you.
