### ISSUE TITLE
what about p and f in s3dis? 

### ISSUE THREAD

**Issue by qifeng22** [mlvlab/SPoTr#24]
p = (x,y,z) in Spatial coordinates
what about f represent?
![image](https://github.com/mlvlab/SPoTr/assets/57132534/35c93613-cfbb-4c62-a157-fcd685b43e24)

**Comment by qifeng22** [comment]
@PJin0

**Comment by PJin0** [comment]
As you know, p indicates spatial coordinates.
f represents features such as colors.
