### ISSUE TITLE
The package problems.

### ISSUE THREAD

**Issue by Gary-bk** [mlvlab/SPoTr#28]
Have u met the problem that u can not install the **torch_scatter** and **pointnet2_batch_cuda** package. Could u give me some suggestions? Thank u.

**Comment by PJin0** [comment]
Thank u for your interest in our paper.

From our knowledge, there is an issue in installing **pointnet2_batch_cuda** package when using CUDA 12.X version. We think that it is a compatibility issue, which is difficult to solve from our level...

Thank you:)

**Comment by Gary-bk** [comment]
> Thank u for your interest in our paper.
> 
> From our knowledge, there is an issue in installing **pointnet2_batch_cuda** package when using CUDA 12.X version. We think that it is a compatibility issue, which is difficult to solve from our level...
> 
> Thank you:)

Thank you for your reply! It works.
