### ISSUE TITLE
Training Classification

### ISSUE THREAD

**Issue by k-hyunji** [mlvlab/SPoTr#29]
hello, first thanks for the classification cfgs! :)
I have some problems while running this code, and really can't tell how to fix this. 
`KeyError: 'BaseCls is not in the models registry'`
Could you help me with this kind of error? some explanations or extra help would be very greatful!

**Comment by PJin0** [comment]
Thanks for your interest in our paper.

We've found that some files were missing in our repo.

We've just corrected it and you can now run the classification code:)

**Comment by k-hyunji** [comment]
Thank you so much! :)
