### ISSUE TITLE
Question about equation (3) and (5)

### ISSUE THREAD

**Issue by djzgroup** [mlvlab/SPoTr#4]
**Equation (3)**

- Since the variable of the SoftMax function is a matrix, a scalar cannot be obtained after calculation through the SoftMax function..

**Equation (5)**

- Why do summation here?
- Even if the summation here is correct, the i subscript can no longer be used here. At least change to j or i'?

**Comment by PJin0** [comment]
** Equation (3) **
The softmax operation in Equation (3) indicates exp(f_i *z_s)/sum(exp(f_i' * z_s)).

**Equation (5) **
That's a typo. We will correct it and thank you for letting me know:).
