### ISSUE TITLE
About Interpolation Feature

### ISSUE THREAD

**Issue by docxmxm** [mlvlab/SPoTr#9]
Hi,

Thank you for this superior work.

I have a question about feature fi.

In code, the Interpolation feature fi was the output of cat[colors, height]. Why is this?
Can I use geometry such as [coord, height] when it applies on the dataset without color?
Or fi could be the SetAbstraction layer used in PointNet++?

Thank you so much for your help!

**Comment by docxmxm** [comment]
Or may I ask you will you pubulish other dataset parameters soon?

**Comment by Rurouni-z** [comment]
may i ask you what is “height” meaning？a point has height? weird to me.

 i found s3dis has 4 features(r,g,b, ?), the last feature is height?

**Comment by PJin0** [comment]
Thank you for the interest to our work and sorry for the late reply.

@docxmxm You can use geometry such as [coord, height] for the data without color.

@Rurouni-z The last feature of s3dis is height. We follow PointNeXt(Neurips 2023) for the data processing.
